name = "StochasticRounding"
uuid = "3843c9a1-1f18-49ff-9d99-1b4c8a8e97ed"
authors = ["Milan Kloewer"]
version = "0.6.3"

[deps]
BFloat16s = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"

[compat]
BFloat16s = "0.1, 0.2"
RandomNumbers = "1.4,1.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
